-- ============================================================
-- ms-analitico | Consulta 5: prediccion de area comun mas visitada
-- PLACEHOLDER: completar cuando exista el catalogo de Glue.
-- ============================================================
--
-- Requerimiento del ACL:
--   "Integrar la tendencia de los usuarios a las areas comunes.
--    Calcular que area comun sera la mas visitada el siguiente mes."
--
-- Fuente: coleccion `reservas` de ms-incidencias (MongoDB), volcada a S3 por
-- ingesta03 y catalogada en Glue.
--
-- Enfoque sugerido (sin salir de SQL):
--   1. Contar reservas por area_comun y por mes.
--   2. Calcular la tendencia: variacion mes a mes con funciones de ventana
--      (LAG / AVG movil sobre los ultimos 3 meses).
--   3. Proyectar el mes siguiente y quedarse con el area de mayor valor.
--
-- Salida esperada:
--   area_comun | visitas_ultimo_mes | promedio_3m | tendencia | proyeccion_prox_mes
--
-- Esqueleto:
-- WITH por_mes AS (
--     SELECT
--         r.area_comun,
--         date_trunc('month', from_iso8601_timestamp(r.fecha_inicio)) AS mes,
--         COUNT(*) AS visitas
--     FROM condominio_db.reservas r
--     WHERE r.estado IN ('CONFIRMADA', 'COMPLETADA')
--     GROUP BY 1, 2
-- ),
-- tendencia AS (
--     SELECT
--         area_comun,
--         mes,
--         visitas,
--         LAG(visitas) OVER (PARTITION BY area_comun ORDER BY mes) AS visitas_mes_previo,
--         AVG(visitas) OVER (
--             PARTITION BY area_comun ORDER BY mes
--             ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
--         ) AS promedio_3m
--     FROM por_mes
-- )
-- SELECT ...
-- ORDER BY proyeccion_prox_mes DESC
-- LIMIT 1;

SELECT 1;  -- TODO: reemplazar por la consulta real
